export const FETCH_USERS_REQUEST="FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE="FETCH_USERS_FAILURE";
export const INCREMENT_PRODUCTS="INCREMENT_PRODUCTS";
export const DECREMENT_PRODUCTS="DECREMENT_PRODUCTS";
export const REMOVE_PRODUCTS="REMOVE_PRODUCTS";
